### PR TITLE
fix: issue where log didn't render long lines

### PR DESCRIPTION
**Pull request by Vafilor**
**What this PR does**:

Fixes an issue where long lines prevented loading of logs.

**Which issue(s) this PR fixes**:

Fixes onepanelio/core#489

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Vafilor** [comment]
Here's a sample log file you can use to test.

**Comment by Vafilor** [comment]
@rushtehrani Do you have a workflow sample that generates timestamps? Just need to make sure this update didn't break that.

**Comment by rushtehrani** [comment]
> Do you have a workflow sample that generates timestamps? Just need to make sure this update didn't break that.

I don't have anything handy. Are you just looking for a loop that outputs timestamps or something else?

**Comment by Vafilor** [comment]
> > Do you have a workflow sample that generates timestamps? Just need to make sure this update didn't break that.
> 
> I don't have anything handy. Are you just looking for a loop that outputs timestamps or something else?

@rushtehrani 

Yeah, something that generates

```
[timestamp] <log text here>
```

That's what the old code checked for.

**Comment by aleksandrmelnikov** [comment]
I'm not sure why this got closed or merged by me.

**Comment by Vafilor** [comment]
@aleksandrmelnikov All good.

**Pull request merged**
